// Use github-app-organization-codekaizen GitHub App credential to clone this repo: https://github.com/codekaizen-github/codekaizen-website-frontend.git
// Then use github-app-user-missiedawes GitHub App credential to push (sync) that repo to
pipeline {
    agent none
    stages {
        // Check out this way to detect if you are building a tag or not: https://www.youtube.com/watch?v=saiCjlJpfdA
        stage('Exit early') {
            agent any
            when {
                not {
                    anyOf {
                        //buildingTag();
                        branch 'main';
                    }
                }
            }
            steps {
                script {
                    echo "Not building. Exiting pipeline with 'NOT_BUILT' status."
                    currentBuild.result = 'NOT_BUILT'
                    error("No changes detected; exiting pipeline.")
                    exit 1
                    return
                }
            }
        }
        stage('Define vars') {
            agent any
            steps {
                script {
                    env.DYNAMIC_REF_NAME = env.TAG_NAME ?: env.GIT_BRANCH
                }
            }
        }
        stage('Push to GitHub') {
            when {
                branch 'main';
            }
            agent {
                docker {
                    image 'mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm'
                    args "-u root --entrypoint ''"
                }
            }
            steps {
                script {
                    withCredentials(bindings: [ \
                        conjurSecretCredential(credentialsId: 'codekaizen-website-github-token-missiedawes-codekaizen-website-frontend-push', variable: 'GITHUB_TOKEN_PUSH')
                    ]) {
                        sh '''
                        env
                        git config --global --add safe.directory $(realpath $(pwd))
                        git remote set-url origin https://USERNAME:${GITHUB_TOKEN_PUSH}@github.com/missiedawes/codekaizen-website-frontend.git
                        git push origin HEAD:${DYNAMIC_REF_NAME} --force
                        '''
                    }
                }
            }
        }
    }
}
